export const lineTypes = [
  { id: 'visible', title: 'Garis benda', pattern: 'Kontinu tebal', thickness: 'Tebal · contoh 0,7 mm', color: '#1589a9', soft: '#e5f7fc', function: 'Menunjukkan kontur dan tepi benda yang terlihat dari arah pandang.', location: 'Kontur luar tutup bantalan dan tepi lengkungan yang terlihat pada tampak depan.', rule: 'Buat garis utuh dengan ketebalan merata. Sudut dan pertemuan kontur harus tersambung.', mistake: 'Jangan menggambar tepi yang tertutup dengan garis benda. Gunakan garis tersembunyi untuk bagian tersebut.', caption: 'Ini garis benda: kontur yang terlihat digambar dengan garis kontinu tebal.', prompt: 'Garis yang menunjukkan tepi benda yang terlihat disebut…' },
  { id: 'dimension', title: 'Garis ukuran & bantu', pattern: 'Kontinu tipis', thickness: 'Tipis · contoh 0,35 mm', color: '#b48725', soft: '#fff7de', function: 'Menunjukkan arah dan batas pengukuran serta nilai ukuran benda.', location: 'Ukuran 98 dan 41 pada tampak depan, 56 pada tampak atas, serta penunjuk radius R30,5.', rule: 'Garis ukuran memakai anak panah. Garis bantu dimulai sedikit terpisah dari kontur dan melewati garis ukuran. Angka harus terbaca tanpa tertimpa garis.', mistake: 'Garis ukuran bukan kontur benda. Jangan mencampur garis bantu ukuran dengan garis sumbu.', caption: 'Garis ukuran punya anak panah dan angka; garis bantu menunjukkan batas yang diukur.', prompt: 'Garis tipis dengan anak panah dan angka 98 berfungsi sebagai…' },
  { id: 'hidden', title: 'Garis tersembunyi', pattern: 'Putus-putus tipis', thickness: 'Tipis · contoh 0,35 mm', color: '#8a61b3', soft: '#f3edfc', function: 'Menunjukkan tepi atau lubang yang tertutup permukaan pada tampak tersebut.', location: 'Dinding lubang baut yang tidak terlihat langsung pada tampak depan, serta tepi rongga di tampak atas.', rule: 'Gunakan strip pendek dan celah yang teratur. Garis tersembunyi membantu membaca bentuk bagian dalam tanpa memotong benda.', mistake: 'Pada potongan, jangan menambahkan semua garis tersembunyi secara otomatis. Arsir dan kontur potongan sudah menjelaskan material yang terpotong.', caption: 'Putus-putus menunjukkan dinding lubang yang tertutup dari arah tampak depan.', prompt: 'Dinding lubang yang tertutup dari arah pengamat ditunjukkan dengan…' },
  { id: 'center', title: 'Garis sumbu', pattern: 'Strip panjang–titik tipis', thickness: 'Tipis · contoh 0,35 mm', color: '#288e70', soft: '#e8f8ef', function: 'Menunjukkan pusat lubang, sumbu, dan kesimetrian benda.', location: 'Tanda pusat pada empat lubang baut serta sumbu tengah tutup bantalan.', rule: 'Pola strip panjang–titik harus berbeda dari putus-putus. Garis sumbu sedikit melampaui bentuk yang ditandai; perpotongan pusat dibuat pada strip.', mistake: 'Jangan mengganti garis sumbu dengan garis utuh atau putus-putus pendek yang sama dengan garis tersembunyi.', caption: 'Garis sumbu melewati pusat lubang; kenali pola strip panjang dan titiknya.', prompt: 'Pusat lubang dan kesimetrian benda ditandai oleh…' },
  { id: 'cutting', title: 'Bidang potong', pattern: 'Strip–titik tebal + panah', thickness: 'Tebal · contoh 0,7 mm', color: '#c06e58', soft: '#fff0e9', function: 'Menunjukkan letak bidang pemotongan dan arah pandang hasil potongannya.', location: 'Bidang A–A melewati tengah kedalaman benda. Panah menunjukkan arah melihat potongan A–A.', rule: 'Tandai jalur bidang potong dengan jelas, beri panah arah pandang, lalu gunakan huruf yang sama di kedua ujung.', mistake: 'Huruf A harus cocok dengan judul potongan A–A. Panah adalah arah pandang, bukan gerakan alat pemotong.', caption: 'A–A menunjukkan tempat benda dipotong; kedua panah menunjukkan arah pandang potongannya.', prompt: 'Garis berpanah dan huruf A yang menentukan letak irisan disebut…' },
  { id: 'hatch', title: 'Arsir potongan', pattern: 'Kontinu tipis, sejajar', thickness: 'Tipis · contoh 0,35 mm', color: '#4384b9', soft: '#eaf3ff', function: 'Menandai material padat yang dilalui bidang potong.', location: 'Material tutup bantalan di atas lengkungan pada potongan A–A. Rongga lengkung tetap kosong.', rule: 'Tarik tipis, sejajar, dan berjarak teratur; umumnya miring 45°. Batasi arsir pada material yang benar-benar terpotong.', mistake: 'Jangan mengarsir lubang atau rongga. Arsir juga harus berhenti tepat pada batas material.', caption: 'Hanya material padat yang diarsir. Rongga setengah lingkaran tetap kosong.', prompt: 'Material padat yang terkena bidang potong ditandai dengan…' },
];

export const lineById = Object.fromEntries(lineTypes.map(type => [type.id, type]));
export const learningOrder = ['visible', 'hidden', 'center', 'dimension', 'cutting', 'hatch'];

export function lineSymbol(type, accessible = false) {
  const common = `fill="none" stroke="currentColor" stroke-linecap="butt" stroke-width="${type.id === 'visible' || type.id === 'cutting' ? 3.6 : 1.8}"`;
  const shape = type.id === 'hatch'
    ? '<path d="M20 29l20-20m0 20 20-20m0 20 20-20m0 20 20-20"/>'
    : type.id === 'dimension' ? '<path d="M10 8V32m100-24v24M10 20H110m-90-4-10 4 10 4m80-8 10 4-10 4"/>'
        : type.id === 'cutting' ? '<path d="M8 20H112" stroke-dasharray="23 4 1.8 4"/><path d="M16 6V34m-4-7 4 7 4-7M104 6V34m-4-7 4 7 4-7" stroke-width="2.5"/>'
        : `<path d="M8 20H112"${type.id === 'hidden' ? ' stroke-dasharray="9 4"' : type.id === 'center' || type.id === 'cutting' ? ' stroke-dasharray="23 4 1.8 4"' : ''}/>`;
  return `<svg class="line-symbol" viewBox="0 0 120 40"${accessible ? ` role="img" aria-label="${type.pattern}"` : ' aria-hidden="true"'}><g ${common}>${shape}</g></svg>`;
}
