import { PROJECTION_VIEWS, createViewDrawing, createProjectionSymbol, createProjectionHero } from './projection-drawing.js';

function methodMap(system) {
  const topY = system === 'eu' ? 69 : 9;
  const sideNames = system === 'eu' ? ['Kanan', 'Kiri'] : ['Kiri', 'Kanan'];
  return `<svg viewBox="0 0 160 100" aria-hidden="true" focusable="false"><g fill="none" stroke="currentColor" stroke-width="1.2" opacity=".4"><path d="M80 32V69M49 50H111"/></g><g font-family="Arial,sans-serif" font-size="9" text-anchor="middle" fill="currentColor"><rect x="60" y="${topY}" width="40" height="23" rx="6" fill="currentColor" opacity=".12"/><text x="80" y="${topY + 15}">Atas</text><rect x="60" y="39" width="40" height="23" rx="6" fill="currentColor" opacity=".24"/><text x="80" y="54" font-weight="700">Depan</text><rect x="12" y="39" width="36" height="23" rx="6" fill="currentColor" opacity=".12"/><text x="30" y="54">${sideNames[0]}</text><rect x="112" y="39" width="36" height="23" rx="6" fill="currentColor" opacity=".12"/><text x="130" y="54">${sideNames[1]}</text></g></svg>`;
}

export function projectionMarkup() {
  const methods = [
    { id: 'eu', name: 'Eropa', angle: 'Sudut pertama', text: 'Tampak atas berada di bawah tampak depan.', note: 'I' },
    { id: 'us', name: 'Amerika', angle: 'Sudut ketiga', text: 'Tampak atas berada di atas tampak depan.', note: 'III' }
  ].map(method => `<button type="button" class="projection-method-card" id="btn-proj-${method.id}" data-system="${method.id}" aria-pressed="${method.id === 'eu'}" aria-label="Pilih proyeksi ${method.name}"><span class="projection-method-symbol">${createProjectionSymbol(method.id)}</span><span class="projection-method-copy"><strong>${method.name} <span>· ${method.angle}</span></strong><span>${method.text}</span><span class="projection-method-tag">Proyeksi sudut ${method.note}</span></span><span class="projection-method-map">${methodMap(method.id)}</span></button>`).join('');
  const faces = Object.entries(PROJECTION_VIEWS).map(([id, view]) => `<div class="cube-face face-${id}" data-face="${id}"><span class="cube-face-label">${view.name}</span><div class="projection-drawing">${createViewDrawing(id)}</div></div>`).join('');
  const chips = Object.entries(PROJECTION_VIEWS).map(([id, view]) => `<button type="button" class="projection-view-chip" data-projection-pick="${id}" aria-pressed="${id === 'front'}"><span style="--view-color:${view.color}" aria-hidden="true"></span>${view.name.replace(/^Tampak /i, '')}</button>`).join('');
  return `<div class="projection-lesson" data-mode="3d" data-system="eu" data-box="true" aria-labelledby="projection-lesson-title">
    <header class="projection-hero">
      <div class="projection-hero-copy"><p class="projection-eyebrow"><span aria-hidden="true">✦</span> KENALI PROYEKSI GAMBAR</p><h2 id="projection-lesson-title">Dari satu benda,<br><span>ke banyak tampak.</span></h2><p>Putar bendanya, kenali setiap pandangan, lalu lihat bagaimana tampaknya disusun pada gambar teknik.</p><svg class="projection-hero-swoosh" viewBox="0 0 120 18" aria-hidden="true"><path d="M3 12Q44 2 114 7" fill="none" stroke="#f5be43" stroke-width="4" stroke-linecap="round"/></svg><button type="button" class="projection-primary" id="projection-start">Coba proyeksi <span aria-hidden="true">→</span></button></div>
      <div class="projection-hero-art" aria-hidden="true"><span class="projection-hero-note">Satu benda,<br>beda cara melihatnya.</span>${createProjectionHero()}</div>
    </header>
    <div class="projection-heading-row"><div><p class="projection-kicker">DUA CARA MENYUSUN TAMPAK</p><h3>Pilih metode proyeksinya.</h3></div><p>Bentuk bendanya sama. Posisi tampaknya yang berubah.</p></div>
    <div class="projection-method-grid" role="group" aria-label="Metode proyeksi">${methods}</div>
    <div class="projection-workspace" id="projection-workspace">
      <article class="projection-preview" aria-labelledby="projection-preview-title">
        <div class="projection-panel-heading"><div><p class="projection-kicker">COBA & BANDINKAN</p><h3 id="projection-preview-title">Lihat benda dari berbagai sisi.</h3></div><span class="projection-badge">120 × 120 × 60 mm</span></div>
        <div class="projection-toolbar"><div class="projection-mode-switch" role="group" aria-label="Mode pratinjau"><button type="button" id="btn-proj-3d" aria-pressed="true">Model 3D</button><button type="button" id="btn-proj-unfold" aria-pressed="false">Susunan 2D</button></div><div class="projection-actions"><button type="button" id="btn-proj-box" aria-pressed="true">Kotak bantu</button><button type="button" id="btn-proj-autorotate" aria-pressed="false">Putar otomatis</button><button type="button" id="btn-proj-reset" aria-label="Kembalikan proyeksi ke posisi awal">↺ Awal</button></div></div>
        <div class="projection-stage-wrap">
          <div class="projection-viewport" id="projection-viewport" tabindex="0" aria-label="Model 3D balok bertingkat. Geser untuk memutar atau gunakan tombol panah.">
            <span class="projection-stage-note">Geser untuk memutar · pilih sisi di bawah</span>
            <div class="glass-box-container projection-glass-box state-3d" id="projection-glass-box" aria-hidden="true"><div class="wireframe-object" id="projection-internal-obj">${['front', 'back', 'bottom', 'base-top', 'tower-top', 'outer-left', 'outer-right', 'step'].map(face => `<div class="block-3d-face block-3d-face--${face}"></div>`).join('')}</div>${faces}</div>
          </div>
          <div class="projection-flat-stage" id="projection-flat-stage" hidden tabindex="0" aria-label="Susunan enam tampak. Pilih tampak pada gambar untuk membaca keterangannya. Setelah diperbesar, geser untuk melihat bagian lain."><div id="projection-flat-host"></div></div>
        </div>
        <div class="projection-zoom" id="projection-zoom" hidden role="group" aria-label="Perbesaran susunan tampak"><span>Perbesar untuk membaca, lalu geser gambar.</span><button type="button" id="btn-proj-zoom-out" aria-label="Perkecil susunan tampak">−</button><button type="button" id="btn-proj-fit" aria-label="Kembalikan ukuran susunan tampak">100%</button><button type="button" id="btn-proj-zoom-in" aria-label="Perbesar susunan tampak">+</button></div>
        <div class="projection-view-picker" role="group" aria-label="Pilih pandangan benda">${chips}</div>
        <p class="projection-stage-status" id="projection-stage-status" role="status" aria-live="polite">Kotak bantu dan keenam tampak langsung ditampilkan. Geser untuk memutar, atau pilih Susunan 2D untuk melihat susunannya.</p>
      </article>
      <aside class="projection-detail" aria-labelledby="projection-view-title"><p class="projection-kicker">PANDANGAN YANG KAMU PILIH</p><h3 id="projection-view-title">Tampak depan</h3><div class="projection-view-art" id="projection-view-preview"></div><p class="projection-view-size" id="projection-view-dimensions"></p><p id="projection-view-desc"></p><div class="projection-view-position"><span>LETAK PADA GAMBAR</span><p id="projection-view-position"></p></div><p class="projection-detail-tip">Klik salah satu tampak pada Susunan 2D untuk mengenali bentuk dan garisnya.</p></aside>
    </div>
    <article class="projection-method-explainer" id="projection-info-box"><div id="projection-iso-symbol" aria-label="Simbol metode proyeksi"></div><div><p class="projection-kicker">PAHAMI CARA MELIHATNYA</p><h3 id="projection-info-title">Proyeksi Eropa · Sudut pertama</h3><p id="projection-info-desc"></p><div class="projection-order" id="projection-order"></div></div></article>
    <div class="projection-learning-grid"><article class="projection-learning-card"><span>01</span><h4>Tentukan tampak depan.</h4><p>Pilih pandangan yang paling jelas menunjukkan bentuk benda. Pada contoh ini, profil undakannya berbentuk L.</p></article><article class="projection-learning-card"><span>02</span><h4>Jaga ukuran antar tampak.</h4><p>Lebar depan sama dengan lebar atas. Tinggi depan sama dengan tinggi samping. Kedalaman terlihat pada atas dan samping.</p></article><article class="projection-learning-card"><span>03</span><h4>Baca rusuk yang tersembunyi.</h4><p>Garis gores pada tampak kiri dan bawah menunjukkan rusuk undakan yang tertutup oleh benda.</p></article></div>
    <details class="projection-footnote"><summary>Catatan gambar teknik</summary><p>Kotak 3D membantu mengenali enam pandangan benda. Perbedaan susunan Eropa dan Amerika ditunjukkan pada mode Susunan 2D. Susunan tampak mengikuti proyeksi ortogonal sudut pertama dan sudut ketiga. Tampak belakang ditempatkan di ujung kanan rangkaian pada contoh ini. Warna dipakai sebagai bantuan belajar; kontur terlihat digambar dengan garis kontinu dan rusuk tersembunyi dengan garis gores.</p><p>Pada gambar kerja, gunakan metode yang ditentukan dan cantumkan simbol proyeksinya pada etiket. Acuan: <a href="https://cdn.standards.iteh.ai/samples/11502/b576be294da54eaab2b3b3fa748b8d1d/ISO-5456-2-1996.pdf" target="_blank" rel="noopener noreferrer">ISO 5456-2 · Orthographic representations</a>.</p></details>
  </div>`;
}
